function data = CyberDiver_read_data_v1(fileID)
data = array2table(fread(fileID, [12, Inf], 'float32')', "VariableNames", ...
    {'time_s', 'current_A', 'force_N', 'position_mm', 'velocity_mmps', ...
    'duty_cycle', 'accel_x_g', 'accel_y_g', 'accel_z_g', 'mode', 'setpoint', 'led'});
end